"""empty message

Revision ID: 0a268bdb81a7
Revises: 6132a27cdd26
Create Date: 2019-09-18 18:52:27.639211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a268bdb81a7'
down_revision = '6132a27cdd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeIngredients', sa.Column('ingredientName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipeIngredients', 'ingredientName')
    # ### end Alembic commands ###
