"""empty message

Revision ID: 243ef6b00710
Revises: a734c69a582a
Create Date: 2020-01-02 15:19:36.975755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243ef6b00710'
down_revision = 'a734c69a582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipeBooks')
    op.drop_table('recipeIngredients')
    op.drop_table('books')
    op.drop_table('collectionFollowers')
    op.drop_table('collections')
    op.drop_index('ix_recipe_recipeName', table_name='recipe')
    op.drop_index('ix_recipe_timestamp', table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('recipeCollections')
    op.drop_table('recipe__steps')
    op.drop_table('bookFollowers')
    op.drop_table('savedrecipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedrecipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('saved_user_id', sa.INTEGER(), nullable=True),
    sa.Column('saved_recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['saved_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookFollowers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_follower_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe__steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('stepNumber', sa.INTEGER(), nullable=True),
    sa.Column('directions', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeCollections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('collection_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipeName', sa.VARCHAR(length=128), nullable=True),
    sa.Column('prepTime', sa.FLOAT(), nullable=True),
    sa.Column('cookTime', sa.FLOAT(), nullable=True),
    sa.Column('Rating', sa.FLOAT(), nullable=True),
    sa.Column('Image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('mainIngredient', sa.VARCHAR(length=64), nullable=True),
    sa.Column('mealType', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_timestamp', 'recipe', ['timestamp'], unique=False)
    op.create_index('ix_recipe_recipeName', 'recipe', ['recipeName'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_by_2', sa.INTEGER(), nullable=True),
    sa.Column('photoURL', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectionFollowers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_follower_id', sa.INTEGER(), nullable=True),
    sa.Column('collection_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['collection_follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('author', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photoURL', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeIngredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredientName', sa.VARCHAR(), nullable=True),
    sa.Column('ingredientAmount', sa.VARCHAR(), nullable=True),
    sa.Column('ingredientUnit', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeBooks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
