"""empty message

Revision ID: 24fad0cc4f6c
Revises: 862c6bdad255
Create Date: 2019-09-19 15:55:08.053130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fad0cc4f6c'
down_revision = '862c6bdad255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createdCollections', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createdCollections')
    # ### end Alembic commands ###
