"""empty message

Revision ID: 274a2ae69f3d
Revises: 243ef6b00710
Create Date: 2020-01-02 15:43:18.111188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274a2ae69f3d'
down_revision = '243ef6b00710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe__steps2')
    op.drop_table('recipeIngredients2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipeIngredients2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe2_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipe2_id'], ['recipe2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe__steps2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('directions', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
