"""empty message

Revision ID: 91e8bf8436b0
Revises: 
Create Date: 2019-09-19 16:03:46.927507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e8bf8436b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('photoURL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredientName', sa.String(), nullable=True),
    sa.Column('ingredientType', sa.String(length=128), nullable=True),
    sa.Column('measurementUnit', sa.String(length=128), nullable=True),
    sa.Column('standardUnitAmount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_ingredientName'), 'ingredients', ['ingredientName'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('bookFollowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_follower_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_2', sa.Integer(), nullable=True),
    sa.Column('photoURL', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeName', sa.String(length=128), nullable=True),
    sa.Column('prepTime', sa.Float(), nullable=True),
    sa.Column('cookTime', sa.Float(), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('Image', sa.String(length=256), nullable=True),
    sa.Column('mainIngredient', sa.String(length=64), nullable=True),
    sa.Column('mealType', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_recipeName'), 'recipe', ['recipeName'], unique=False)
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    op.create_table('collectionFollowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_follower_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeBooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeCollections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeIngredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('ingredientName', sa.String(), nullable=True),
    sa.Column('ingredientAmount', sa.String(), nullable=True),
    sa.Column('ingredientUnit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe__steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('stepNumber', sa.Integer(), nullable=True),
    sa.Column('directions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_savedRecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_user_id', sa.Integer(), nullable=True),
    sa.Column('saved_recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['saved_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_savedRecipes')
    op.drop_table('recipe__steps')
    op.drop_table('recipeIngredients')
    op.drop_table('recipeCollections')
    op.drop_table('recipeBooks')
    op.drop_table('collectionFollowers')
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_recipeName'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('collections')
    op.drop_table('bookFollowers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ingredients_ingredientName'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('books')
    # ### end Alembic commands ###
