"""empty message

Revision ID: a734c69a582a
Revises: 4922823fff42
Create Date: 2019-09-28 18:56:04.425245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a734c69a582a'
down_revision = '4922823fff42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_2', sa.Integer(), nullable=True),
    sa.Column('photoURL', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections2')
    # ### end Alembic commands ###
