"""first update

Revision ID: cb64ba9f42a4
Revises: 
Create Date: 2019-08-28 14:59:19.813770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb64ba9f42a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredientName', sa.String(), nullable=True),
    sa.Column('ingredientType', sa.String(length=128), nullable=True),
    sa.Column('measurementUnit', sa.String(length=128), nullable=True),
    sa.Column('standardUnitAmount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_ingredientName'), 'ingredients', ['ingredientName'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeName', sa.String(length=128), nullable=True),
    sa.Column('prepTime', sa.Integer(), nullable=True),
    sa.Column('cookTime', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('Image', sa.String(length=256), nullable=True),
    sa.Column('mainIngredient', sa.String(length=64), nullable=True),
    sa.Column('mealType', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_recipeName'), 'recipe', ['recipeName'], unique=False)
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    op.create_table('recipe__steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('stepNumber', sa.Integer(), nullable=True),
    sa.Column('directions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('ingredientAmount', sa.Float(), nullable=True),
    sa.Column('ingredientUnit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe__steps')
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_recipeName'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ingredients_ingredientName'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
