"""empty message

Revision ID: fc8e6c312659
Revises: 91e8bf8436b0
Create Date: 2019-09-23 21:10:33.521342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8e6c312659'
down_revision = '91e8bf8436b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedrecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_user_id', sa.Integer(), nullable=True),
    sa.Column('saved_recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['saved_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_savedRecipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_savedRecipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('saved_user_id', sa.INTEGER(), nullable=True),
    sa.Column('saved_recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['saved_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('savedrecipes')
    # ### end Alembic commands ###
