"""empty message

Revision ID: fea1efc2a87c
Revises: 80138f96d07c
Create Date: 2019-09-19 14:03:55.634121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea1efc2a87c'
down_revision = '80138f96d07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'user', ['created_by'], ['username'])
    # ### end Alembic commands ###
